### ISSUE TITLE
Running issues

### ISSUE THREAD

**Issue by SciGno** [MaxM65dia/vscode-go-prof#1]
Hello,

This looks like a great extension for VSCode.  Except that it is not working for me.  When I click on mem profile, the benchmark stays running forever.  Also, the icon does not show up in the Activity bar.

**Comment by MaxM65dia** [comment]
Hello,

Would it be possible to create some code for a repro?

**Comment by SciGno** [comment]
I'm not sure what to do to reproduce the issue.  This is a sample code:

```go
type SomeStruct struct {
	value string
}

func MyStruct() *SomeStruct {
	return &SomeStruct{"data"}
}

func Benchmark_MyStruct(b *testing.B) {
	for i := 0; i < b.N; i++ {
		MyStruct()
	}
}
```
Is this what you are asking for?

**Comment by MaxM65dia** [comment]
Thank for the sample code. This looks like a simple case to me. If you experience this issue on this code, then it seems that there is some issue with running pprof tool.

Please try to run pprof in a terminal and see if it is available.
If it is not installed then pprof can be installed using the following command line: "go get -u github.com/google/pprof"

**Comment by SciGno** [comment]
I was able to run pprof from multiple terminals, like iTerm, MS Code terminal buy executing:
$GOPATH/bin/pprof

I'm still having the same issue.  This is what I see:
![Screen Shot 2019-05-14 at 10 41 33 AM](https://user-images.githubusercontent.com/9068880/57707222-3e2d2100-7635-11e9-9141-7430fdbef2d1.png)

**Comment by MaxM65dia** [comment]
btw, which OS you are working with?

**Comment by SciGno** [comment]
I'm using Mac OSX Mojave.

Also, I'm able to run it this way:
`go tool pprof somefile.test prof.cpu`

**Comment by matepeter90** [comment]
Hi!
It's indeed a really useful extension, but when I wanted to use it, I had the same issue.
I tried SciGno's example after my benchmark function didn't work, but the experience was the same, it stuck at Running.
I enabled the Developer tools and in the Console after clicking 'cpu profile' an error message appeared:
```
ERR spawn go.exe ENOENT: Error: spawn go.exe ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

I'm using Ubuntu so it's correct, it won't find go.exe.
Then I installed Go, VSCode and the extension on Windows and tried SciGno's example which worked like a charm there, even the extension's icon appeared on the activity bar.

So if I can guess, I would say finding the go binary on different OSes could be the culprit.

**Comment by MaxM65dia** [comment]
Hi,

We have fixed this issue, please try to update to the latest version and let us know how it works.

**Comment by matepeter90** [comment]
Hi,

I updated and tried the new version. It works for me on Ubuntu, thank you very much!

**Comment by SciGno** [comment]
Hello,

Thanks for the update and fix.  I tested the update in Mac OSX and it works perfectly.

**Comment by MaxM65dia** [comment]
Hello,

Thank you for confirming the fix works, We would greatly appreciate if you could leave us a review on VSCode marketplace. Thanks!
